# "데이터 분석 numpy 기초 문법 노트북"
> "20201년 여름방학 데이터분석을 위한 python 기초문법"

- toc:true
- branch: master
- badges: true
- comments: true
- author: jangeunhye
- categories: [Python, 데이터분석, numpy]

In [2]:
리스트 = [[1,2,3], [4,5,6], [7,8,9]]
리스트[0][0]
리스트[2][0]


7

In [5]:
import numpy as np

리스트 = [[1,2,3], [4,5,6], [7,8,9]]
리스트 = np.array(리스트)
리스트 * 2
리스트 + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [7]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [9]:
a = np.arange(20).reshape(4, 5) #reshape(row, column)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [12]:
a = np.arange(20).reshape(2, 2, 5) # 3차원
a[0][1][1]

6

In [19]:
a = np.arange(15).reshape(3, 5)
a
a.shape
a.ndim # 몇차원인지
a.dtype.name # 데이터 타입
a.itemsize
a.size # flat한 데이터 사이즈
type(a) 

numpy.ndarray

In [21]:
np.zeros((3, 4)) #0으로 생성

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
np.ones((2, 3), dtype=np.int16) 

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [26]:
np.empty((2, 3))

array([[4.68485207e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [28]:
np.arange(0, 2, 0.3) # arrange에서는 소수점 안됨

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [31]:
np.linspace(0, 10, 20) # 0부터 10까지의 수를 20개 출력

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [35]:
리스트 = [[10,2,3], [4,5,6], [7,8,9]]
a = np.array(리스트)
# a.sum(), sum(리스트) # sum(리스트)는 에러납니다.
a.min(), min(리스트)
a.max(), max(리스트) # 두개는 출력하는 결과도 다릅니다. 0번째 숫자만 비교함 10과 4와 7을 -> 10이 제일 크니까 [10, 2, 3]을 출력

(10, [10, 2, 3])

In [39]:
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
b.sum(axis=0) # cilumn기준으로 row끼리 더한 것(세로) axis = 축 
b.sum(axis=1) # row기준으로 colimn끼리 더한 것(가로)
b.sum() # flat하게 모두 더한 것

66

In [45]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [49]:
b.T # 잘써요!
# b.transpose() # 잘 안써요

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [55]:
a = np.array([[1, 2], [3, 4]])
b = np.floor([[5, 6], [7, 8]])
np.vstack((a, b))
np.hstack((a, b))

array([[1., 2., 5., 6.],
       [3., 4., 7., 8.]])

In [51]:
a = np.arange(12).reshape(3, 4)
b = a > 4
b 

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [52]:
b.sum() # 매우 많이 사용

7